In [1]:
import numpy as np

In [2]:
my_list=[10,20,30,40]
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [5]:
my_numpy_array=np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max()

40

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.zeros(9)


array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.random.random(5)

array([0.66878508, 0.09929445, 0.12553725, 0.63033435, 0.96926029])

In [11]:
my_list1=[1,2]

In [12]:
my_list2 = [3,4]

In [16]:
my_list1 + my_list2

[1, 2, 3, 4]

In [17]:
my_numpy_array1 = np.array(my_list1)

In [18]:
my_numpy_array2 = np.array(my_list2)

In [19]:
my_numpy_array1 + my_numpy_array2

array([4, 6])

In [20]:
my_numpy_array1 * my_numpy_array2

array([3, 8])

In [21]:
my_numpy_array1 / my_numpy_array2

array([0.33333333, 0.5       ])

In [22]:
 my_numpy_array1 *5

array([ 5, 10])

In [23]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [24]:
other_array=np.array([10,20,30,40])

In [26]:
other_array.min()

10

In [27]:
other_array.sum()

100

In [28]:
my_numpy_array1

array([1, 2])

In [29]:
#other_array+ my_numpy_array1 #

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [30]:
# araange and indexing

In [33]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
np_array =np.arange(0,10)

In [37]:
np_array[0]

0

In [38]:
np_array[-1]

9

In [39]:
np_array[1:4]

array([1, 2, 3])

In [40]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
np_array[2:6:2]

array([2, 4])

In [42]:
# RANDOM

In [43]:
np.random.random(4)

array([0.00613183, 0.08606031, 0.68917937, 0.28728087])

In [45]:
np.random.randn(4,4)

array([[ 1.15119352, -0.11259861,  0.43883117, -0.2587435 ],
       [-0.0572342 , -0.13020734, -1.39223354, -0.94735728],
       [ 0.81035738,  0.43431004,  0.88734589,  0.01797197],
       [ 0.86752896, -0.07494507,  0.73747821, -1.39296308]])

In [1]:
# MATRİX

In [2]:
my_matrix = [[5,10] ,[15,20]]
my_matrix[0]

[5, 10]

In [6]:
import numpy as np  # row,colomn

In [8]:
numpy_matrix = np.array([[5,10] ,[15,20]])
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [9]:
numpy_matrix[1][0]

15

In [10]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
first_array = np.array([[10,20] , [30,40]])
second_array = np.array([[5,15] , [25,35]])


In [14]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [15]:
thir_array = np.array([[50,60]])

In [16]:
thir_array

array([[50, 60]])

In [17]:
thir_array + first_array

array([[ 60,  80],
       [ 80, 100]])

In [19]:
thir_array.shape

(1, 2)

In [20]:
# matrix multiplication

In [21]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [22]:
# dot product

In [35]:
first = np.array([[10,20,30]])
first

array([[10, 20, 30]])

In [36]:
first.shape

(1, 3)

In [37]:
secon = np.array([[2,3] ,[2,3] , [2,3]])

In [38]:
secon

array([[2, 3],
       [2, 3],
       [2, 3]])

In [39]:
secon.shape

(3, 2)

In [41]:
result = first.dot(secon)
result

array([[120, 180]])