In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([54, 96, 62,  1, 66, 75, 75, 40, 62, 90, 39, 21, 90, 37, 63, 40, 46,
       67, 42, 13])

In [4]:
new_array > 25

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False])

In [5]:
new_array[new_array > 25]

array([54, 96, 62, 66, 75, 75, 40, 62, 90, 39, 90, 37, 63, 40, 46, 67, 42])

In [6]:
new_array[new_array < 25]

array([ 1, 21, 13])

In [7]:
# transpose and reshape

In [8]:
matrix_array = np.array([[10,20] , [20,30] ,[30,40]])

In [9]:
matrix_array.shape

(3, 2)

In [11]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [12]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
random_array =np.random.random((6,1))

In [17]:
random_array

array([[0.16239383],
       [0.85050654],
       [0.01619754],
       [0.28576757],
       [0.98452919],
       [0.32346589]])

In [19]:
random_array.reshape(2,3)

array([[0.16239383, 0.85050654, 0.01619754],
       [0.28576757, 0.98452919, 0.32346589]])

In [20]:
random_array.reshape(3,2)

array([[0.16239383, 0.85050654],
       [0.01619754, 0.28576757],
       [0.98452919, 0.32346589]])

In [21]:
# z-score

In [22]:
data = np.array([10,12,15,18,21,100,105])

In [23]:
# outlier

In [27]:
mean = np.mean(data)

In [28]:
mean

40.142857142857146

In [29]:
data.sum() / len(data)

40.142857142857146

In [30]:
std = np.std(data)

In [31]:
std

39.60313325060665

In [32]:
z_scores = data - mean / std

In [33]:
z_scores

array([  8.98637169,  10.98637169,  13.98637169,  16.98637169,
        19.98637169,  98.98637169, 103.98637169])

In [35]:
z_scores [z_scores > 10 ]

array([ 10.98637169,  13.98637169,  16.98637169,  19.98637169,
        98.98637169, 103.98637169])

In [36]:
data [z_scores > 10 ]

array([ 12,  15,  18,  21, 100, 105])

In [37]:
# 2x+3y =8 and 5x + 7y = 19

In [38]:
# coefficient

In [39]:
A = np.array([[2,3] ,[5,7]])

In [40]:
# constant

In [41]:
B = np.array([8,19])

In [42]:
solution = np.linalg.solve(A,B)

In [43]:
solution

array([1., 2.])